/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kodkod_engine_satlab_OpenWBOPartition */

#ifndef _Included_kodkod_engine_satlab_OpenWBOPartition
#define _Included_kodkod_engine_satlab_OpenWBOPartition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    make
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_make
  (JNIEnv *, jclass);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    addVariables
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_addVariables
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    addHardClause
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_addHardClause__J_3I
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    addHardClause
 * Signature: (JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_addHardClause__JI_3I
  (JNIEnv *, jobject, jlong, jint, jintArray);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    addSoftClauses
 * Signature: (JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_addSoftClauses__JI_3I
  (JNIEnv *, jobject, jlong, jint, jintArray);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    addSoftClauses
 * Signature: (JII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_addSoftClauses__JII_3I
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    solve
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_OpenWBOPartition
 * Method:    valueOf
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_OpenWBOPartition_valueOf
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
